version: '3'
services:
  api:
    image: api
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
      # args:
      #   - MYSQL_HOST=${MYSQL_HOST}
      # volumes:
      #   - "./api:/home/node/app"
    ports:
      - 80:80
    restart: "always"
    # environment:
    #   MYSQL_HOST: ${MYSQL_HOST}
