name: "This is my actions"

inputs:
  AZURE_SP:
    description: "Credentials of the Azure SP"
    required: true

runs:
  steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ inputs.AZURE_SP }}

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az group list