name: "Terraform plan"

inputs:
  WORKING_DIR:
    description: "working directory"
    required: true
  AZURE_SP:
    description: "Credentials of the Azure SP"
    required: true
  RESOURCE_GROUP_NAME:
    description: "Name of the resource group"
    required: true
  STORAGE_ACCOUNT_NAME:
    description: "Name of the storage account"
    required: true
  CONTAINER_NAME:
    description: "Name of the container where the state files are"
    required: true
  STATE_FILE:
    description: "Name of the state files"
    required: true
  

runs:
  using: "composite"
  steps:

    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false
        #https://stackoverflow.com/questions/69925970/how-to-save-terraform-output-variable-into-a-github-action-s-environment-variabl

    - name: Terraform Init
      id: init
      run: terraform init
      shell: bash
      working-directory: ${{ inputs.WORKING_DIR }}

    - name: Terraform Apply
      id: apply
      run: terraform apply -auto-approve
      continue-on-error: false
      shell: bash
      working-directory: ${{ inputs.WORKING_DIR }}

    - name: Terraform Output
      id: output
      run: terraform output -json > ./output.json
      continue-on-error: false
      shell: bash
      working-directory: ${{ inputs.WORKING_DIR }}
        