name: "Create storage account and container"

inputs:
  WORKING_DIR:
    description: "working directory"
    required: true

runs:
  using: "composite"
  steps:
    - name: "Check inputs"
      run: ls -ltr
      shell: bash
      working-directory: ${{ inputs.WORKING_DIR }}

    # - name: Azure Login
    #   uses: azure/login@v1
    #   with:
    #     creds: ${{ inputs.AZURE_SP }}
    
    # - name: Azure Login
    #   uses: azure/login@v1
    #   with:
    #     creds: ${{ inputs.AZURE_SP }}

    - uses: hashicorp/setup-terraform@v2

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: false
      working-directory: ${{ inputs.WORKING_DIR }}

    # - name: Terraform Init
    #   id: init
    #   run: terraform init