version: '3'
services:
  api:
    image: crfptcpacr.azurecr.io/api
    container_name: api-container
    build:
      context: .
      dockerfile: Dockerfile
      # args:
      #   - MYSQL_HOST=${MYSQL_HOST}
      # volumes:
      #   - "./api:/home/node/app"
    ports:
      - 8080:80
    restart: "always"
    # environment:
    #   MYSQL_HOST: ${MYSQL_HOST}
